apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    labels:
        app: frontend
    name: frontend
spec:
    replicas: 2
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            labels:
                app: frontend
        spec:
            containers:
            - image: magalixcorp/sample-api:v1
              imagePullPolicy: IfNotPresent
              name: frontend
              volumeMounts:
              - name: config-volume
                mountPath: /app/config.json
                subPath: config.json
            volumes:
                - name: config-volume
                  configMap:
                    name: app-config



# Code for running a Node Js SERVER:

# # An official Docker image for Node.js
# FROM node:10-alpine

# # Working directory for the containerised application
# WORKDIR /src/app

# # This copies significant package.json files to the current directory
# COPY package*.json ./
# # Install essential Node.js dependencies
# RUN npm install

# COPY . .

# # Opens up this port on the Docker container
# EXPOSE 8080

# # This starts the Docker application
# CMD [ "npm", "start" ]